import { notFound } from 'next/navigation';
import { prisma } from '@/lib/prisma';
import { AdminFrame } from '@/components/admin/AdminFrame';
import { formatTnd } from '@/lib/currency';
import { updateOrderStatus } from '@/app/admin/actions';

export default async function OrderDetail({ params }: { params: { id: string } }) {
  const order = await prisma.order.findUnique({ where: { id: params.id }, include: { customer: true, address: true, items: { include: { customizations: true } }, emails: true } });
  if (!order) notFound();
  return <AdminFrame><h1 className="font-display text-5xl">{order.orderNumber}</h1><div className="mt-8 grid gap-8 lg:grid-cols-[1fr_360px]"><div className="space-y-6"><div className="card p-6"><h2 className="font-display text-3xl">Items</h2>{order.items.map((item) => <div key={item.id} className="border-b border-espresso/10 py-4"><p className="font-semibold">{item.productNameFr} × {item.quantity}</p><p className="text-sm text-bark/70">Color: {item.colorLabelFr || '-'}</p>{item.customizations.map((c) => <p className="text-xs text-bark/60" key={c.id}>{c.groupLabelFr}: {c.textValue || c.optionLabelFr || (c.booleanValue ? 'Yes' : '')}</p>)}<p className="mt-2">{formatTnd(item.lineTotal)}</p></div>)}</div><div className="card p-6"><h2 className="font-display text-3xl">Email log</h2>{order.emails.map((email) => <p key={email.id} className="text-sm">{email.type} · {email.status} · {email.recipient}</p>)}</div></div><aside className="space-y-6"><div className="card p-6"><h2 className="font-display text-3xl">Customer</h2><p>{order.customer.firstName} {order.customer.lastName}</p><p>{order.customer.phone}</p><p>{order.customer.secondPhone}</p><p>{order.customer.email}</p><p className="mt-3 text-sm text-bark/70">{order.address.addressLine}, {order.address.city}, {order.address.governorate}, {order.address.postalCode}</p><p className="mt-3 text-sm">Notes: {order.notes || '-'}</p></div><form action={updateOrderStatus} className="card p-6"><input type="hidden" name="id" value={order.id} /><label className="label">Status</label><select className="input" name="status" defaultValue={order.status}>{['PENDING_CONFIRMATION','CONFIRMED','IN_PRODUCTION','READY_TO_SHIP','SHIPPED','DELIVERED','CANCELLED'].map((s) => <option key={s}>{s}</option>)}</select><label className="label mt-4">Admin notes</label><textarea className="input" name="adminNotes" defaultValue={order.adminNotes || ''} /><button className="btn-primary mt-5 w-full">Update status</button><p className="mt-3 text-xs text-bark/60">Changing to CONFIRMED sends customer and owner emails.</p></form><div className="card p-6"><p>Subtotal: {formatTnd(order.subtotal)}</p><p>Shipping: {formatTnd(order.shippingFee)}</p><p className="mt-3 text-xl font-semibold">Total: {formatTnd(order.total)}</p></div></aside></div></AdminFrame>;
}
